### PR TITLE
A PR For issue #420

### PR DESCRIPTION
**Pull request by SteafanMrZhou**
As mentioned issue 420:
1.RingBufferFields constructor method optimized
In RingBufferFields constructor metod:
`this.bufferSize = sequencer.getBufferSize();`
this line initialized the bufferSize field,so the next line
`this.entries = (E[]) new Object[sequencer.getBufferSize() + 2 * BUFFER_PAD];`
sequencer.getBufferSize() is not neccessaury for getting bufferSize,only from the bufferSize to initialing entries is well.
Cause sequencer.getBufferSize() method have one question:
In JVM, the sequencer's memory allocated in heap,each access sequencer require searching  heap,this progress is slowly compare to cache.
2.RingBuffer cache-line optimized
In the final class RingBuffer,the Disruptor defined a series of variables in the below:
`protected byte
        p10, p11, p12, p13, p14, p15, p16, p17,
        p20, p21, p22, p23, p24, p25, p26, p27,
        p30, p31, p32, p33, p34, p35, p36, p37,
        p40, p41, p42, p43, p44, p45, p46, p47,
        p50, p51, p52, p53, p54, p55, p56, p57,
        p60, p61, p62, p63, p64, p65, p66, p67,
        p70, p71, p72, p73, p74, p75, p76, p77;`
But the RingBuffer extends RingBufferFields,RingBufferFields extends RingBufferPad,the variables mentioned above already exist in RingBufferFields.
According to the object publishing principle,when the RingBuffer is published,all objects related to RingBuffer will be published,so,the published RingBuffer that in cache contains p10-p77 from RingBufferFields.
In order to save the memory space of the ringbuffer object itself and improve the processing speed of ringbuffer, it is not recommended to define these variables repeatedly in the ringbuffer class.

### CODE REVIEW

**Comment by Palmr** [comment]
1. This "optimisation" is actually a fair comment. We could indeed just use `bufferSize` when creating the `entries` array. In the grand scheme of things, this will have no bearing on performance however. Unless you're constantly creating new RingBuffer objects. But then you likely have other issues to contend with.
2. The meaning of these duplicated padding fields might not be immediately obvious but they do serve a use in the current configuration. The variables defined on `RingBufferPad` will be cache line padding before the fields defined in `RingBufferFields`. This is because `RingBufferFields` extends `RingBufferPad` and the Java spec says any fields from extended classes will be laid out in memory first. Then `RingBuffer` extends `RingBufferFields` so when laid out in memory it will have the padding from `RingBufferPad`, followed by the fields from `RingBufferFields`, followed by the padding in `RingBuffer`. This will add cache-line padding protection for all the fields in `RingBufferFields`. The output of [JOL](https://github.com/openjdk/jol) can be seen below, showing this layout.

```
com.lmax.disruptor.RingBuffer object internals:
OFF  SZ        TYPE DESCRIPTION                   VALUE
  0   8             (object header: mark)         N/A
  8   4             (object header: class)        N/A
 12   1        byte RingBufferPad.p10             N/A
 13   1        byte RingBufferPad.p11             N/A
 14   1        byte RingBufferPad.p12             N/A
 15   1        byte RingBufferPad.p13             N/A
 16   1        byte RingBufferPad.p14             N/A
 17   1        byte RingBufferPad.p15             N/A
 18   1        byte RingBufferPad.p16             N/A
 19   1        byte RingBufferPad.p17             N/A
 20   1        byte RingBufferPad.p20             N/A
 21   1        byte RingBufferPad.p21             N/A
 22   1        byte RingBufferPad.p22             N/A
 23   1        byte RingBufferPad.p23             N/A
 24   1        byte RingBufferPad.p24             N/A
 25   1        byte RingBufferPad.p25             N/A
 26   1        byte RingBufferPad.p26             N/A
 27   1        byte RingBufferPad.p27             N/A
 28   1        byte RingBufferPad.p30             N/A
 29   1        byte RingBufferPad.p31             N/A
 30   1        byte RingBufferPad.p32             N/A
 31   1        byte RingBufferPad.p33             N/A
 32   1        byte RingBufferPad.p34             N/A
 33   1        byte RingBufferPad.p35             N/A
 34   1        byte RingBufferPad.p36             N/A
 35   1        byte RingBufferPad.p37             N/A
 36   1        byte RingBufferPad.p40             N/A
 37   1        byte RingBufferPad.p41             N/A
 38   1        byte RingBufferPad.p42             N/A
 39   1        byte RingBufferPad.p43             N/A
 40   1        byte RingBufferPad.p44             N/A
 41   1        byte RingBufferPad.p45             N/A
 42   1        byte RingBufferPad.p46             N/A
 43   1        byte RingBufferPad.p47             N/A
 44   1        byte RingBufferPad.p50             N/A
 45   1        byte RingBufferPad.p51             N/A
 46   1        byte RingBufferPad.p52             N/A
 47   1        byte RingBufferPad.p53             N/A
 48   1        byte RingBufferPad.p54             N/A
 49   1        byte RingBufferPad.p55             N/A
 50   1        byte RingBufferPad.p56             N/A
 51   1        byte RingBufferPad.p57             N/A
 52   1        byte RingBufferPad.p60             N/A
 53   1        byte RingBufferPad.p61             N/A
 54   1        byte RingBufferPad.p62             N/A
 55   1        byte RingBufferPad.p63             N/A
 56   1        byte RingBufferPad.p64             N/A
 57   1        byte RingBufferPad.p65             N/A
 58   1        byte RingBufferPad.p66             N/A
 59   1        byte RingBufferPad.p67             N/A
 60   1        byte RingBufferPad.p70             N/A
 61   1        byte RingBufferPad.p71             N/A
 62   1        byte RingBufferPad.p72             N/A
 63   1        byte RingBufferPad.p73             N/A
 64   1        byte RingBufferPad.p74             N/A
 65   1        byte RingBufferPad.p75             N/A
 66   1        byte RingBufferPad.p76             N/A
 67   1        byte RingBufferPad.p77             N/A
 68   4         int RingBufferFields.bufferSize   N/A
 72   8        long RingBufferFields.indexMask    N/A
 80   4         E[] RingBufferFields.entries      N/A
 84   4   Sequencer RingBufferFields.sequencer    N/A
 88   1        byte RingBuffer.p10                N/A
 89   1        byte RingBuffer.p11                N/A
 90   1        byte RingBuffer.p12                N/A
 91   1        byte RingBuffer.p13                N/A
 92   1        byte RingBuffer.p14                N/A
 93   1        byte RingBuffer.p15                N/A
 94   1        byte RingBuffer.p16                N/A
 95   1        byte RingBuffer.p17                N/A
 96   1        byte RingBuffer.p20                N/A
 97   1        byte RingBuffer.p21                N/A
 98   1        byte RingBuffer.p22                N/A
 99   1        byte RingBuffer.p23                N/A
100   1        byte RingBuffer.p24                N/A
101   1        byte RingBuffer.p25                N/A
102   1        byte RingBuffer.p26                N/A
103   1        byte RingBuffer.p27                N/A
104   1        byte RingBuffer.p30                N/A
105   1        byte RingBuffer.p31                N/A
106   1        byte RingBuffer.p32                N/A
107   1        byte RingBuffer.p33                N/A
108   1        byte RingBuffer.p34                N/A
109   1        byte RingBuffer.p35                N/A
110   1        byte RingBuffer.p36                N/A
111   1        byte RingBuffer.p37                N/A
112   1        byte RingBuffer.p40                N/A
113   1        byte RingBuffer.p41                N/A
114   1        byte RingBuffer.p42                N/A
115   1        byte RingBuffer.p43                N/A
116   1        byte RingBuffer.p44                N/A
117   1        byte RingBuffer.p45                N/A
118   1        byte RingBuffer.p46                N/A
119   1        byte RingBuffer.p47                N/A
120   1        byte RingBuffer.p50                N/A
121   1        byte RingBuffer.p51                N/A
122   1        byte RingBuffer.p52                N/A
123   1        byte RingBuffer.p53                N/A
124   1        byte RingBuffer.p54                N/A
125   1        byte RingBuffer.p55                N/A
126   1        byte RingBuffer.p56                N/A
127   1        byte RingBuffer.p57                N/A
128   1        byte RingBuffer.p60                N/A
129   1        byte RingBuffer.p61                N/A
130   1        byte RingBuffer.p62                N/A
131   1        byte RingBuffer.p63                N/A
132   1        byte RingBuffer.p64                N/A
133   1        byte RingBuffer.p65                N/A
134   1        byte RingBuffer.p66                N/A
135   1        byte RingBuffer.p67                N/A
136   1        byte RingBuffer.p70                N/A
137   1        byte RingBuffer.p71                N/A
138   1        byte RingBuffer.p72                N/A
139   1        byte RingBuffer.p73                N/A
140   1        byte RingBuffer.p74                N/A
141   1        byte RingBuffer.p75                N/A
142   1        byte RingBuffer.p76                N/A
143   1        byte RingBuffer.p77                N/A
Instance size: 144 bytes
Space losses: 0 bytes internal + 0 bytes external = 0 bytes total
```

I cannot merge this PR in its current form.

However I would accept just the first change, to use `bufferSize`. Though please remove the old line instead of commenting it out.

**Comment by SteafanMrZhou** [comment]
@Palmr I modified the previous code, please review again,thanks.
1.For the overall framework of Disruptor itself, maybe this change is not enough to affect the performance of the framework itself, but, as you said, when we need a lot of new RingBuffer objects, the performance problems I mentioned before may occur, which is also The code optimization method officially recommended by java, that is, if we initialize the member variable of the class in the constructor of the class, if we do not need to modify the member variable in the future, we should use it directly, and it is not recommended to obtain it repeatedly.
2. I sincerely accept this design idea.

**Comment by SteafanMrZhou** [comment]
The PR added the performance tag by you,what of the meaning?
If its about Disruptor performance or RingBuffer performance,i want to try sovle,but not in the PR,please.

**Comment by noakcn** [comment]
你发的邮件我已经收到了。
                                    以上为自动回复邮件

**Pull request merged**
