### PR TITLE
Remove the concept of WorkerPool

### PR DESCRIPTION
**Pull request by Palmr**
Issue #323 - `WorkerPool` and `WorkProcessor` have been removed, no more `Disruptor::handleEventsWithWorkerPool`

### CODE REVIEW

**Comment by grumpyjames** [comment]
Farewell, WorkerPool, king of work queues, whose long and faithful friendship those who knew you won't forget.

**Comment by leroniris** [comment]
Why remove WorkerPool And WorkProcessor ?

**Comment by noakcn** [comment]
你发的邮件我已经收到了。
                                    以上为自动回复邮件

**Comment by Palmr** [comment]
> Why remove WorkerPool And WorkProcessor ?

See the linked issue https://github.com/LMAX-Exchange/disruptor/issues/323

**Pull request merged**
